# Generated by Django 2.2 on 2022-04-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
